If UPSTREAM_REPO is undefined, warn about it
This needs to be defined as global variable in the actual project so we can
fetch our images from there. Where it isn't defined, the skopeo command will
fail. Let's at least warn about it.

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>

diff --git a/templates/debian.yml b/templates/debian.yml
--- a/templates/debian.yml
+++ b/templates/debian.yml
@@ -307,11 +307,13 @@
 
     # check if our image is already in the current registry
     - skopeo inspect docker://$CI_REGISTRY_IMAGE/$DISTRO/$REPO_SUFFIX_LOCAL:$DISTRO_TAG > /dev/null && exit 0 || true
-
     # check if our image is already in the upstream registry
-    - skopeo inspect docker://$CI_REGISTRY/$UPSTREAM_REPO/$DISTRO/$REPO_SUFFIX:$DISTRO_TAG > /dev/null
-      && touch .upstream || true
-
+    - if [[ -z "$UPSTREAM_REPO" ]];
+      then
+        echo "WARNING! Variable \$UPSTREAM_REPO is undefined, cannot check for images" ;
+      else
+        skopeo inspect docker://$CI_REGISTRY/$UPSTREAM_REPO/$DISTRO/$REPO_SUFFIX:$DISTRO_TAG > /dev/null && touch .upstream || true ;
+      fi
     # copy the original image into the current project registry namespace
     # we do 2 attempts with skopeo copy at most
     - if [ -f .upstream ] ;
