Add the "if not exists" thing magic to fedora
Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>

diff --git a/templates/fedora.yml b/templates/fedora.yml
--- a/templates/fedora.yml
+++ b/templates/fedora.yml
@@ -14,7 +14,7 @@
 #                    be run once the packages have been installed
 #
 # The resulting image will be pushed in the local registry, under:
-#    $CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$CI_PIPELINE_ID
+#     $CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$CI_PIPELINE_ID
 #
 # It is then up to the caller to promote the image as latest or any tag
 # that would be convenient
@@ -55,3 +55,43 @@
 
     # push the container image to the registry
   - podman push --quiet $CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$CI_PIPELINE_ID
+
+
+# This will create or reuse a debian image based on the following variables:
+#
+#  - UPSTREAM_REPO:  the upstream project on this gitlab instance where we might
+#                    find the given tag (for example: 'wayland/weston')
+#  - FEDORA_VERSION: the fedora version (28, 29, rawhide, etc...)
+#  - FEDORA_RPMS:    list of packages that needs to be installed
+#  - FEDORA_SCRIPT:  if set, this path should point to a bash script that will
+#                    be run once the packages have been installed
+#  - FEDORA_TAG:     tag to copy the image from the upstream registry. If the
+#                    tag does not exist, create a new build and tag it
+#
+# The resulting image will be pushed in the local registry, under:
+#     $CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$CI_PIPELINE_ID
+# and $CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$FEDORA_TAG
+#
+
+.fedora@container-ifnot-exists:
+  extends: .fedora@container-build
+  before_script:
+  # log in to the registry
+  - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+
+  # check if our image is already in the current registry
+  - skopeo inspect docker://$CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$FEDORA_TAG > /dev/null && exit 0 || true
+
+  # copy the original image into the current project registry namespace
+  - skopeo copy docker://$CI_REGISTRY/$UPSTREAM_REPO/debian/$FEDORA_VERSION:$FEDORA_TAG
+                docker://$CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$FEDORA_TAG && exit 0 || true
+  after_script:
+  # if we did not build, or if there was a failure, exit
+  # (the exit status does not matter here)
+  - if [[ ! -e .success ]] ;
+    then
+      exit 0;
+    fi
+
+  - skopeo copy docker://$CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$CI_PIPELINE_ID
+                docker://$CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$FEDORA_TAG
